# Generated by Django 6.1.1 on 2026-09-17 10:29

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('country_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('flag_url', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
                ('weather_description', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'weather snapshot',
                'verbose_name_plural': 'weather snapshots',
                'ordering': ['country_code'],
            },
        ),
    ]
