# Generated by Django 6.1.1 on 2026-09-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherSnapshot',
            new_name='CountrySnapshot',
        ),
        migrations.AlterModelOptions(
            name='countrysnapshot',
            options={'ordering': ['country_code'], 'verbose_name': 'country snapshot', 'verbose_name_plural': 'country snapshots'},
        ),
    ]
